name: CI/CD - MCP Server + Adapter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-pythonv4
        with:
          python-version: '3.12.11'
      
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run syntax check
        run: |
          python3 -m py_compile openwebui_adapter.py universal_llm_client.py alfresco_mcp_server.py

docker-check:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check Docker Compose validity
      run: docker compose config